### PR TITLE
Collate for color tag

### PR DESCRIPTION
**Pull request by A0155428B**

### CODE REVIEW

**Comment by davidten** [comment]
@A0155428B can you provide a description about what this PR is about?

**Comment by A0155428B** [comment]
this is collate for color tag features, collate is an app used for grading, details are in v1.2

**Comment by davidten** [comment]
what i meant was describe what the PR does, not what you are doing.

For example, adds an author tag

**Comment by davidten** [comment]
@A0155428B passing only because looks relatively simple, in the future do provide a description about what exactly changes in the PR.

**Comment by davidten** [comment]
@A0155428B also do label and milestone your own PRs.

**Pull request merged**
