### PR TITLE
Updates icon

### PR DESCRIPTION
**Pull request by A0155428B**

### CODE REVIEW

**Comment by A0155428B** [comment]
whats the reason for using 32x32 ?

**Comment by davidten** [comment]
1. The image you replaced is 32x32
2. The image name is _32

**Comment by A0155428B** [comment]
how about changing the name to _256?  is a better defined image better?

**Comment by davidten** [comment]
A higher res image would require more time to load, if you change a 32x32 you should keep it at 32x32. You can have a new image at 256x256, but always be backwards compatible

**Pull request merged**
